blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/H5MNcFW63r
    about: For general questions and support
  - name: Matrix Room
    url: https://matrix.to/#/#yt-dlp:matrix.org
    about: For general questions and support (Matrix)
  - name: Docs/Wiki
    url: https://github.com/yt-dlp/yt-dlp/wiki
    about: Read the documentation before opening an issue
